### ISSUE TITLE
Linux dark mode requires specific theme

### ISSUE THREAD

**Issue by ProjectMoon** [LionyxML/auto-dark-emacs#19] opened 2022-11-22 11:40 UTC
This is a copy and paste of my Reddit comment.

Unless I'm missing something, this only works if you have the `Yaru-dark` theme installed and in use. This isn't a standard GNOME theme (usually it is Adwaita).

It would make more sense to provide configurable variables for the light/dark GTK theme names. Or better yet, make use of the `/org/gnome/desktop/interface/color-scheme` dconf setting. This is the new Gnome standard way of doing dark mode. When it's light, it's `default`, and when it's dark, it's `prefer-dark`. I think it's available from Gnome 42 onwards.

Edit: The `\n` should be removed from the check as well, because `string-trim` gets rid of it, and thus the equality check fails when `\n` is there.

**Comment by ProjectMoon** [comment] 2022-11-22 11:59
Based on another comment in the same Reddit thread, it is probably best to utilize dbus to expose a similar hook system like on Mac OS: https://git.sr.ht/%7Edsemy/emacs-config/tree/master/item/init.d/init-interfaces.el#L44

**Comment by manueldeljesus** [comment] 2022-11-22 16:01
I can confirm that auto-dark-mode does not work on Fedora with customized themes. Most probably for the reasons explained above. I look forward to test new versions of the package with updated functionality.

**Comment by real-or-random** [comment] 2022-11-26 13:12
> Based on another comment in the same Reddit thread, it is probably best to utilize dbus to expose a similar hook system like on Mac OS: [git.sr.ht/%7Edsemy/emacs-config/tree/master/item/init.d/init-interfaces.el#L44](https://git.sr.ht/%7Edsemy/emacs-config/tree/master/item/init.d/init-interfaces.el#L44)

I can confirm that the dbus code works well (GNOME 43.1 with custom theme), and this seems much better than a polling solution.

<details>
<summary>Full snippet for spacemacs users</summary>

```elisp
  (defvar init-interfaces-dbus-color-scheme-change-functions nil
    "Special hook run when a color scheme change is detected through D-Bus.
  Each function in this hook is called with a single argument, `light'
  or `dark', according to the current color scheme.")

  (add-hook 'init-interfaces-dbus-color-scheme-change-functions
            (lambda (mode)
              (if (eq mode 'dark)
                (spacemacs/load-theme 'solarized-dark nil t)
                (spacemacs/load-theme 'solarized-light nil t))))

  (when-let (((require 'dbus nil t))
            (service (car (member "org.freedesktop.portal.Desktop"
                                  (dbus-list-activatable-names :session)))))
    (dbus-register-signal
    :session service
    "/org/freedesktop/portal/desktop" "org.freedesktop.portal.Settings"
    "SettingChanged"
    (lambda (path var val)
      (and (string= path "org.freedesktop.appearance")
            (string= var "color-scheme")
            (run-hook-with-args
            'init-interfaces-dbus-color-scheme-change-functions
            (pcase (car val) (0 'light) (1 'dark))))))
    (run-hook-with-args
    'init-interfaces-dbus-color-scheme-change-functions
    (pcase (caar (dbus-call-method
                  :session service
                  "/org/freedesktop/portal/desktop"
                  "org.freedesktop.portal.Settings" "Read"
                  "org.freedesktop.appearance" "color-scheme"))
      (0 'light) (1 'dark))))
```
</details>

**Comment by LionyxML** [comment] 2022-12-09 01:44
Hello there!
Sorry I've been out for a while. Personal stuff :(

I agree with you guys that a solution base on d-bus integration might be a better approach for Linux users.

Anyone willing to tweak the code and open a PR? I might do it myself in the future, but currently I don't even have Linux installed here around.

**Comment by real-or-random** [comment] 2022-12-11 18:31
The above snippet for spacemacs handles the setting at startup via `run-hook-with-args`. (By the way, I think the only spacemacs-specific thing here is `spacemacs/load-theme`.)

**Comment by ProjectMoon** [comment] 2022-12-14 23:00
Hmm, you are right. Somehow I had the hook defined after the rest of the code, and it didn't run on startup. But after putting the hook definition above, it works.

**Comment by LionyxML** [comment] 2022-12-31 20:46
Hello there good people! :)

@J3RN's PR #20  has been merged and is already available on MELPA.

`emacs-auto-dark` now uses D-Bus as default theme checker for GNU/Linux.

**Closed** 2023-01-04 00:31 UTC

**Comment by manueldeljesus** [comment] 2023-01-04 08:07
It does not seem to set the correct theme on startup. Is there need still to configure a hook to make the initial check?

**Comment by real-or-random** [comment] 2023-01-04 13:29
> It does not seem to set the correct theme on startup. Is there need still to configure a hook to make the initial check?

Are you on spacemacs by any chance? I'm on spacemacs and I just figured out that I need to replace the `load-theme` with `spacemacs/load-theme` in `auto-dark--set-theme` to make this work on startup...

 I'm not sure how to approach this issue properly, to be honest. Maybe there should be a possibility to tell spacemacs to just get out of the way with their theme logic. Setting `dotspacemacs-themes` to `nil` doesn't achieve this.

**Comment by manueldeljesus** [comment] 2023-01-04 16:51
Auto-dark works if, after opening Emacs, I disable it manually and re-enable it manually. At that point it loads the correct theme. May anyone please share how are you configuring it on your config file? I may be doing something wrong there and thus the problem on opening.

**Comment by LionyxML** [comment] 2023-01-04 17:22
Hello there!

I really think these feedbacks are great! But doing so from this "closed" issue may not get to all people involved.

I just opened the issue #25 

May we migrate this to there?
